server.config.type: test

logging:
  org.hibernate.SQL: debug
  level:
    root: INFO
    sql: ERROR

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    session:
      timeout: 10m